version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --proxy-headers --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s